spring:
  application:
    name: ms-registro-venta
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:mysql://localhost:3306/db_ventas?createDatabaseIfNotExist=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083

jwt:
  secret: MiSuperClaveSecretaParaTodosLosMicroserviciosDeLaTienda2024

carrito:
  url: http://localhost:8082

catalogo:
  url: http://localhost:8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: 127.0.0.1
    instance-id: 127.0.0.1:${spring.application.name}:${server.port}

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/db_ventas?createDatabaseIfNotExist=true

carrito:
  url: http://ms-carrito:8082

catalogo:
  url: http://ms-catalogo:8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: ms-registro-venta
    instance-id: ms-registro-venta:${server.port}
