spring:
  application:
    name: ms-despacho
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:mysql://localhost:3306/db_despacho?createDatabaseIfNotExist=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8087

jwt:
  secret: MiSuperClaveSecretaParaTodosLosMicroserviciosDeLaTienda2024

venta:
  url: http://localhost:8083

sucursal:
  url: http://localhost:8086

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: 127.0.0.1
    instance-id: 127.0.0.1:${spring.application.name}:${server.port}

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/db_despacho?createDatabaseIfNotExist=true

venta:
  url: http://ms-registro-venta:8083

sucursal:
  url: http://ms-sucursales:8086

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: ms-despacho
    instance-id: ms-despacho:${server.port}
